services:
  db:
    container_name: myPostgresContainer
    image: postgres:15.1
    environment:
      POSTGRES_USER: hamza
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5532:5432"
    networks:
      - db
    restart: unless-stopped

  hamzakhan-customerapi:
    container_name: hamzakhan-customerapi
    image: dangerouslefty/hamzakhan-customerapi
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped


  pgadmin:
    container_name: myPgadminContainer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - db
    restart: unless-stopped
    depends_on:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
  pgadmin: